# Set some defaults to tianbot racecar launch environment

: ${TIANBOT_RACECAR_BASE:=compact}
: ${TIANBOT_RACECAR_RGBD_CAMERA:=realsense_d435}
: ${TIANBOT_RACECAR_LIDAR:=rplidar_a3}
: ${TIANBOT_RACECAR_STEERING_REVERSE:=normal}
: ${TIANBOT_RACECAR_THROTTLE_REVERSE:=normal}


#Exports
export TIANBOT_RACECAR_BASE
export TIANBOT_RACECAR_RGBD_CAMERA
export TIANBOT_RACECAR_LIDAR
export TIANBOT_RACECAR_STEERING_REVERSE
export TIANBOT_RACECAR_THROTTLE_REVERSE
